---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      properties:
        acks: all
        retries: 5
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: item-event-topic