---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      retries: 5
      acks: all
    template:
      default-topic: item-event-topic