server:
  port: 8080
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      properties:
        acks: all # acks: all is same as acks = -1
        retries: 5
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: item-event-topic