spring:
  kafka:
    producer:
      bootstrap-servers: <kafka-broker-host>:<port>
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer