server:
  port: 8080
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      properties:
        acks: all
        retries: 5
    admin:
      properties:
        bootstrap.servers: localhost:29092
    template:
      default-topic: item-event-topic